using Xunit;
using Moq;
using TerminalShell.ViewModels;
using TerminalShell.Core;
using TerminalShell.Core.Config;
using TerminalShell.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace TerminalShell.Tests.ViewModels;

public class MainViewModelTests
{
    private readonly Mock<IConfigManager> _mockConfigManager;
    private readonly AppConfig _testConfig;

    public MainViewModelTests()
    {
        _mockConfigManager = new Mock<IConfigManager>();
        _testConfig = new AppConfig
        {
            Terminals = new List<TerminalConfig>
            {
                new TerminalConfig { Name = "Terminal 1", ShowInMainWindow = true },
                new TerminalConfig { Name = "Terminal 2", ShowInMainWindow = true }
            }
        };

        _mockConfigManager.Setup(m => m.Config).Returns(_testConfig);
    }

    [Fact]
    public void HideTerminalCommand_ShouldSetShowInMainWindowToFalse_AndSaveConfig()
    {
        // Arrange
        var viewModel = new MainViewModel(_mockConfigManager.Object);
        // Wait for async load to simulate (though constructor calls async void, we can wait or assume fast enough for mock)
        // In this test, we are testing the Command execution, not the startup sync.
        
        // We need a TerminalSession instance that matches the config name
        var sessionToHide = new TerminalSession("Terminal 1");

        // Act
        // Verify Command exists (it's generated by RelayCommand source generator, but we haven't implemented it yet - RED PHASE)
        // Since we can't compile if we call non-existent method, we skip the call in RED phase check or comment it out.
        // But for TDD, we expect compilation error or runtime error. 
        // As an AI, I will write the code that WOULD call it, knowing it will fail compilation, 
        // OR I write the implementation first if I can't run partial compilation.
        
        // However, "Strict TDD" says write failing test first.
        // C# requires me to define the property to compile.
        // So I will assume the property is there but throws NotImplemented, OR I just define the skeleton in VM.
        
        // I'll proceed to implementation directly after this step to make it compile.
        
        viewModel.HideTerminalCommand.Execute(sessionToHide);

        // Assert
        Assert.False(_testConfig.Terminals.First(t => t.Name == "Terminal 1").ShowInMainWindow);
        _mockConfigManager.Verify(m => m.Save(), Times.Once);
    }

    [Fact]
    public void BuildBaseWindowTitle_ShouldUseExeNameWithoutExtension()
    {
        Assert.Equal("ServiceShell v3.96", RuntimeAppIdentity.BuildBaseWindowTitle("ServiceShell", "3.96"));
    }

    [Fact]
    public void BuildExternalIconPath_ShouldUseExeSiblingIco()
    {
        string expected = Path.Combine(@"D:\apps", "ServiceShell.ico");
        string actual = RuntimeAppIdentity.BuildExternalIconPath(@"D:\apps\ServiceShell.exe");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void BuildTrayTooltipText_ShouldReuseBaseWindowTitle()
    {
        Assert.Equal("ServiceShell v3.96", RuntimeAppIdentity.BuildTrayTooltipText("ServiceShell v3.96"));
    }

    [Fact]
    public void BuildTrayRestartMenuText_ShouldFollowExeName()
    {
        Assert.Equal("Restart ServiceShell", RuntimeAppIdentity.BuildTrayRestartMenuText("ServiceShell"));
    }

    [Fact]
    public void BuildWindowTitle_ShouldAppendSoundAndRemoteSuffix()
    {
        string actual = MainViewModel.BuildWindowTitle("ServiceShell v3.96", true, "[remote: 18080]");

        Assert.Equal("ServiceShell v3.96 [sound] [remote: 18080]", actual);
    }

    [Fact]
    public void BuildWindowTitle_ShouldKeepBaseTitleWhenSuffixesAreEmpty()
    {
        string actual = MainViewModel.BuildWindowTitle("ServiceShell v3.96", false, "   ");

        Assert.Equal("ServiceShell v3.96", actual);
    }

    [Fact]
    public void ReloadSessions_ShouldLoadThemeStateFromConfig()
    {
        _testConfig.MainWindowTheme = new MainWindowThemeConfig
        {
            InputContainerBackgroundColor = "#112233",
            SendButtonBackgroundColor = "#445566",
            SendButtonHoverForegroundColor = "#778899",
            WaitForUserInputHighlightColor = "#AABBCC",
            ContextMenuGutterBackgroundColor = "#DDEEFF"
        };

        MainViewModel viewModel = new(_mockConfigManager.Object);

        Assert.Equal("#112233", viewModel.ThemeState.InputContainerBackgroundColor);
        Assert.Equal("#445566", viewModel.ThemeState.SendButtonBackgroundColor);
        Assert.Equal("#778899", viewModel.ThemeState.SendButtonHoverForegroundColor);
        Assert.Equal("#AABBCC", viewModel.ThemeState.WaitForUserInputHighlightColor);
        Assert.Equal("#DDEEFF", viewModel.ThemeState.ContextMenuGutterBackgroundColor);
    }

}
